theme: jekyll-theme-time-machine
title: Stephen Fisher Data Science
description: My name is Stephen Fisher.  I am a junior Computer Engineer at Lehigh University. This page will display some of my projects that I have done in my data sciences courses and on my own to further my learning!
