theme: jekyll-theme-minimal
title: Welcome from Stephen Fisher
description: My name is Stephen Fisher.  I am a junior Computer Engineer at Lehigh University. This page will display some of my projects that I am doing for my current data science course. 
INSERT LINK: [TEST LINK](espn.com)
