theme: jekyll-theme-minimal
title: Stephen Fisher Data Science
description: My name is Stephen Fisher.  I am a junior Computer Engineer at Lehigh University. This page will display some of my projects that I am doing for my current data science course. 
